"""Stable telemetry, grouped by orchestration dependencies (not 30 functions)."""

NAMES = [
    "Run intake",
    "Project / target / environment resolution",
    "Authorization & permission evaluation",
    "Credential capability binding",
    "Target safety validation",
    "Repository/environment snapshot",
    "Requirement/context ingestion",
    "Change/diff analysis",
    "Risk classification",
    "Prior trusted-context retrieval",
    "Test/capability inventory discovery",
    "Impact mapping",
    "Test-plan generation",
    "Plan policy validation",
    "Execution workspace & tool readiness",
    "Static/lint execution",
    "Build/type/package verification",
    "Unit execution",
    "Integration execution",
    "API/contract execution",
    "Browser smoke/E2E execution",
    "Accessibility execution",
    "Visual execution",
    "Web diagnostics",
    "Defensive security baseline",
    "Evidence sealing & failure normalization",
    "Reproduction & flaky/environment discrimination",
    "Fix verification & relevant regression",
    "Gate decision + learning/audit update",
    "Final evidence report",
]
CHECK_STAGE = {
    "lint": 16,
    "build": 17,
    "type": 17,
    "unit": 18,
    "regression": 19,
    "integration": 19,
    "api": 20,
    "smoke": 21,
    "browser_e2e": 21,
    "accessibility": 22,
    "web_diagnostics": 24,
    "security_dependency_scan": 25,
    "security_headers": 25,
}
TERMINAL = {"SUCCEEDED", "FAILED", "ERROR", "BLOCKED", "SKIPPED", "CANCELLED"}
TRANSITIONS = {
    "PENDING": {"READY", "SKIPPED", "BLOCKED", "CANCELLED"},
    "READY": {"RUNNING", "BLOCKED", "CANCELLED"},
    "RUNNING": TERMINAL | {"AWAITING_APPROVAL"},
    "AWAITING_APPROVAL": {"SUCCEEDED", "BLOCKED", "CANCELLED"},
}
