from __future__ import annotations

import json
from pathlib import Path
from typing import Any

from qa_agent.models import Report, to_dict, utc_now


class ReviewQueue:
    """File-backed human approval gate for reports generated by local runs."""

    def __init__(self, root: str | Path = "artifacts/review_queue") -> None:
        self.root = Path(root)
        self.root.mkdir(parents=True, exist_ok=True)

    def submit(self, report: Report) -> Path:
        record = {
            "report": to_dict(report),
            "approval_status": "pending",
            "review_notes": "",
            "reviewed_at": None,
        }
        path = self._path(report.id)
        path.write_text(json.dumps(record, indent=2, default=str), encoding="utf-8")
        return path

    def approve(self, report_id: str, notes: str = "") -> Path:
        return self._set_status(report_id, "approved", notes)

    def reject(self, report_id: str, notes: str = "") -> Path:
        return self._set_status(report_id, "rejected", notes)

    def get(self, report_id: str) -> dict[str, Any]:
        path = self._path(report_id)
        if not path.exists():
            raise FileNotFoundError(f"Review record not found for report: {report_id}")
        return json.loads(path.read_text(encoding="utf-8"))

    def list_records(self) -> list[dict[str, Any]]:
        return [json.loads(path.read_text(encoding="utf-8")) for path in sorted(self.root.glob("*.json"), reverse=True)]

    def _set_status(self, report_id: str, status: str, notes: str) -> Path:
        record = self.get(report_id)
        record["approval_status"] = status
        record["review_notes"] = notes
        record["reviewed_at"] = utc_now()
        path = self._path(report_id)
        path.write_text(json.dumps(record, indent=2, default=str), encoding="utf-8")
        return path

    def _path(self, report_id: str) -> Path:
        return self.root / f"{report_id}.json"
